<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SignUpTest"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="22.636">
    <properties></properties>

            <testcase
                name="signUp"
                time="22.636"
                classname="com.ExtramarksWebsite_TestCases.SignUpTest">

            <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying SignUp Test Functionality expected [Signup_Pass] but found []">
                <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying SignUp Test Functionality expected [Signup_Pass] but found []
                org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)com.ExtramarksWebsite_TestCases.SignUpTest.signUp(SignUpTest.java:315)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeMethod(Invoker.java:661)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)java.lang.Thread.run(Thread.java:748)
]]>
            </failure>
    </testcase>


</testsuite>
