<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="E4795_Tech" name="com.ExtramarksWebsite_TestCases.SignUpTest" tests="1" failures="1" timestamp="14 Feb 2020 15:32:20 GMT" time="205.119" errors="0">
  <testcase name="signUp" time="205.119" classname="com.ExtramarksWebsite_TestCases.SignUpTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying SignUp Test Functionality expected [Signup_Pass] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying SignUp Test Functionality expected [Signup_Pass] but found []
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.ExtramarksWebsite_TestCases.SignUpTest.signUp(SignUpTest.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- signUp -->
</testsuite> <!-- com.ExtramarksWebsite_TestCases.SignUpTest -->
