<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="E4795_Tech" name="com.ExtramarksWebsite_TestCases.StudentNotesTest" tests="6" failures="3" timestamp="14 Feb 2020 15:32:20 GMT" time="2484.829" errors="0">
  <testcase name="addNotes" time="169.826" classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying add notes functionality expected [AddNotes_PASS] but found [AddNotes_Records_Not_Display_on_Grid_FAIL]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying add notes functionality expected [AddNotes_PASS] but found [AddNotes_Records_Not_Display_on_Grid_FAIL]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.ExtramarksWebsite_TestCases.StudentNotesTest.addNotes(StudentNotesTest.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- addNotes -->
  <testcase name="editNotes" time="482.716" classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying edit notes functionality expected [EditNotes_PASS] but found [EditNotes_Records_not_Displayed_on_Grid_FAIL]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying edit notes functionality expected [EditNotes_PASS] but found [EditNotes_Records_not_Displayed_on_Grid_FAIL]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.ExtramarksWebsite_TestCases.StudentNotesTest.editNotes(StudentNotesTest.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- editNotes -->
  <testcase name="deleteNotes" time="355.102" classname="com.ExtramarksWebsite_TestCases.StudentNotesTest"/>
  <testcase name="shareNotes" time="392.032" classname="com.ExtramarksWebsite_TestCases.StudentNotesTest"/>
  <testcase name="verifysharedNotes" time="814.175" classname="com.ExtramarksWebsite_TestCases.StudentNotesTest"/>
  <testcase name="viewLesson" time="270.978" classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying View Lesson from notes functionality Actual Result :  Expected Result : ,XII,Sociology: Indian Society,Introducing Indian Society expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying View Lesson from notes functionality Actual Result :  Expected Result : ,XII,Sociology: Indian Society,Introducing Indian Society expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.ExtramarksWebsite_TestCases.StudentNotesTest.viewLesson(StudentNotesTest.java:385)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- viewLesson -->
</testsuite> <!-- com.ExtramarksWebsite_TestCases.StudentNotesTest -->
